#!/usr/bin/env python3
"""Update the deterministic catalog block in README.md."""

from __future__ import annotations

import argparse

from _lib import ROOT, CheckError, load_json

OUTPUT = ROOT / "README.md"
START = "<!-- catalog:start -->"
END = "<!-- catalog:end -->"
HEADER = "<!-- Generated by scripts/build_catalog.py; do not edit this block. -->"


def render_catalog() -> str:
    lines = [HEADER, ""]
    marketplace_path = ROOT / "marketplace.json"
    if not marketplace_path.exists():
        lines.extend(["No plugins have been added yet.", ""])
        return "\n".join(lines)

    marketplace = load_json(marketplace_path)
    manifests = [
        ROOT / entry["path"] / "plugin.json" for entry in marketplace["plugins"]
    ]
    lines.extend(
        [
            "| Plugin | Version | Description | Skills | MCP |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for path in manifests:
        data = load_json(path)
        capabilities = data["capabilities"]
        skill_count = len(list(path.parent.glob("skills/*/SKILL.md")))
        lines.append(
            f"| `{data['name']}` | `{data['version']}` | {data['description']} | "
            f"{skill_count} | "
            f"{'yes' if capabilities['mcp'] else 'no'} |"
        )
    return "\n".join(lines)


def render(readme: str) -> str:
    if readme.count(START) != 1 or readme.count(END) != 1:
        raise CheckError(f"{OUTPUT.name} must contain one catalog marker pair")
    prefix, remainder = readme.split(START, 1)
    _, suffix = remainder.split(END, 1)
    return f"{prefix}{START}\n{render_catalog()}\n{END}{suffix}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating when the README catalog block is stale",
    )
    args = parser.parse_args()
    if not OUTPUT.exists():
        raise CheckError(f"{OUTPUT.name} is missing")
    current = OUTPUT.read_text(encoding="utf-8")
    rendered = render(current)
    if args.check:
        if current != rendered:
            raise CheckError("README.md catalog is stale; run scripts/build_catalog.py")
        print("OK: README.md catalog is current")
        return
    if current != rendered:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print("updated README.md catalog")
    else:
        print("README.md catalog already current")


if __name__ == "__main__":
    try:
        main()
    except CheckError as error:
        raise SystemExit(f"error: {error}") from error
